### ISSUE TITLE
The Kiss of Ra

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#183]
- **text:** if acting vampire somehow unlock him can play same action because action no reach resolution,pls add that,i dint know that,and im sure another people dint know,or they dint sure
- **link:** https://www.vekn.net/forum/rules-questions/79001-the-question-of-the-month-action-fizzles#101492

**Comment by Snodig** [comment]
Covered by general rulings. Any action that ends (before resolution) can be attempted again.

**Comment by warwar1980** [comment]
trust me,beter to we have this writen in rules,if people know that they dint ask. i think idea in codex is to we can find fast link rules

**Comment by Snodig** [comment]
What you're proposing creates a problem on its own:
If every card that is affected by a general ruling should be linked to such a ruling, then any card *not* linked to that same ruling is presumed to be unaffected. This means that the codex should either have perfect coverage for such links, or none at all.

**Comment by warwar1980** [comment]
I think is idea of codex site to ruling be fast searchable. 
as you can see me link question is fresh,and people dont know answer,or they dont sure in answer

**Comment by Snodig** [comment]
I believe my point remains valid. What the goal is for krcg is for Lionel to decide.

**Comment by lionel-panhaleux** [comment]
You both make great arguments, and I'll try to take them all into consideration.

@warwar1980 is right that my default stance to choose what to include is simply "if the question was asked, it means people could not figure it out, so let's include it". I try to stay humble as I'm no RD, and prefer to go with "no question is stupid" and try not to dismiss questions or rulings I find trivial. Given how the rulings list is managed, it's actually pretty easy to add a single ruling for multiple cards. However, making sure the coverage is perfect, as says @Snodig, can be tricky if too many cards are involved. So as a rule of thumb, I'd say let's include rulings when they cover **less than 50 cards**. So far for example, I'v included rulings on:

- Cards that end/cancel an action
- Blood Brothers Circles
- Cards played at action declaration and after action resolution
- Black Hand and Seraph Keywords
- etc.

I've not included:

- Wording Templates confirmations (that's a *lot* of cards), although this is still a point I'm considering. The question "Is that usable only once per X?" is very common, and although seasoned players invariably answer "Yeah, During X, do Y template", it would still be worth it to have it in the KRCG rulings since so many people ask.
- General rulings on some card types or turn steps (eg. "Action modifiers cannot be played by a vampire in torpor unless that vampire is the acting minion.")

Consider the discussion on https://github.com/lionel-panhaleux/krcg/issues/82 for example. I could be swayed into reconsidering, of course: nothing is set in stone. For the matter at hand (current issue), I'd say let's add the ruling where it matters. It can probably be formulated to include all intricacies, which are not so clear in the rulebook (ie. action can be taken again by the same vampire, but it has consumed Veil / Enkil). The number of cards to cover should be manageable.

**Comment by Snodig** [comment]
The sad truth is that the reason rulings like this one perhaps *should* be connected to this card, is that the rulebook is not clear on what constitutes a performed vs ended action (for the purposes of NRA).
That being the case, I am amenable to agreeing with you that this is necessary.
Not too happy about it. I guess I should go complain to Ankha instead.

**Comment by Snodig** [comment]
Thanks for taking the time to explain your stance, Lionel.
