### ISSUE TITLE
Hide the Heart

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#252]
- **text:** Regarding this ruling (#3); it is unclear whose block attempts must be declared before playing HTH in the event of an undirected action where the HTH player is the predator. I believe only the prey must declare first (passing the impulse to HTH player), but the rulings are all regarding D-actions. Regardless, the text should be explicit as to who must declare blocks ("he" is ambigious).
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/vJQTPYtp-Eg/m/6_nkxd28-v8J

**Comment by Snodig** [comment]
The ambiguity is actually a secondary point. The text should clarify whether all eligible blockers (including or not including, depending on how it works) must declare blocks, rather than the text explicitly describing a D-action.

A suggestion, but feel free to paraphrase (or correct) accordingly:
`If other Methuselah are eligible to block, the Methuselah playing Hide the Hearth must wait until all other eligible blockers declare their block attempts or until he is next in line to declare blocks (following normal sequencing rules). [LSJ 20100507][PIB 20150820]`

**Comment by lionel-panhaleux** [comment]
Thanks for the precision. A better wording would be neat, but this has to be as compact as possible. For people wondering about the details, they can always click the ruling to access the full discussion / explanation on the topic. 

Maybe something like: `Sequencing applies (see Rulebook). For example, if another Methuselah is targeted by the action, they must declare if they attempt or decline to block before you can play Hide the Heart.`

What do you think?

**Comment by lionel-panhaleux** [comment]
Something as compact as `One must be next in line to declare blocks (following normal sequencing rules) to pay Hide the Heart. [LSJ 20100507][PIB 20150820]` would be precise, but I fear it's not very clear if you're not a bit of a rule monger to begin with 😁
