### ISSUE TITLE
raptor-psyche

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#37]
people in serbia are confused about that and they think how not need redraw after psyche,i finaly find pascal answer,so after psyche you need to redraw cards,and discard again: http://www.vekn.net/forum/rules-questions/63650-clarification-regarding-raptors#65506

that is reason whu i made new topic for that,but ankha dint answer,but other 2 did : http://www.vekn.net/forum/rules-questions/78603-raptor-and-psyche#99695

**Comment by warwar1980** [comment]
in first link i cannot open james link

**Comment by lionel-panhaleux** [comment]
OK I think this link could do better if this is all about raptor: 
https://groups.google.com/d/msg/rec.games.trading-cards.jyhad/SZehI8SwAc4/shpyPIdsHxUJ

In this one LSJ's answer is direct. I find if funny it confuses people: I mean, "it could not be otherwise": card starts a new combat, that means old combat ends and new combat begins. How could you not replenish you hand and discard again ?

Anyhow, including it.

**Comment by lionel-panhaleux** [comment]
For your future rulings searches: when a VEKN link doesn't work, just try to add "www." before "vekn.net" in the link in your browser, this should fix it: VEKN.net without www used to work, but doesn't anymore 😉 

Also, if you can't find a ruling on VEKN, searching the jyhad google group for LSJ rulings is quite easy: go in the group, in the search fiel, click the arrow and search "posted by: lsj"
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/1032179/80837247-bbf78d00-8bf6-11ea-80f8-0f29f38f66d4.png">

**Comment by warwar1980** [comment]
ok. I know for google groups but more like if find ankha answer,or ankha answer with lsj link,you know,some rules from lsj time is changes
