### ISSUE TITLE
Burning Wrath

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#41]
I must say i got confused and must read more time links in this pages: https://codex-of-the-damned.org/card-search/index.html?card=Burning%20Wrath

link from tom is confused by me,link from lsj where him say is all damage aggr is clear

**Comment by lionel-panhaleux** [comment]
This is because the rulings have changed since TOM time.

I'll remove the first link, it just adds to the confusion. I kept it because I think if the hand strike is not preventable, the Burning Wrath gives an unpreventable aggravated strike (ie. inherits the "unpreventable"). I'm not sure if this is a likely or even possible situation, though.

So, let's just remove the first link 😉
