### ISSUE TITLE
Force of Personality

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#595]
- **text:** The interpretation of this ruling is outright wrong. Ruling clearly states you replace action card as the last thing you do in "as announced" window.
- **link:** https://www.vekn.net/forum/rules-questions/77210-touch-of-clarity-and-fast-reaction-is-posible-to-play-with-locked-minion?start=6#92308

**Comment by lionel-panhaleux** [comment]
That's not what this ruling is about. That ruling was selected as a reference because it's one of the broadest / most explanatory rulings on "as announced" windows, but it does state what the interpretation here explains: you replace the action card before you play the modifier (in the ruling, they use Seduction as an example, but the same applies to Force of Personality). The ruling pointed to here is explaining the intricacies of when wake and cancellation effects happen in relation to the replacement and potential subsequent modifiers (which is not in the interpretation but could be useful for completeness), but you misunderstood it.
