### ISSUE TITLE
Yoruba Shrine

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#617]
- **text:** can be used to cancel a (d) action toward all assamite controlled by an unique player
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/zBOoZ0t_y5Q/m/Jf6HWo_t9HwJ?pli=1

**Comment by kschaefe** [comment]
I don't think I posted this, but IIRC MtG rules on targeting were (and maybe still are) that "global" effects" things that deal 2 damage to every creature, don't target the creatures individually.  One could argue that MtG players needs this clarification, even if it's in the rulebook.

Though I'd argue that you're inferring from the rulebook, instead of just applying the rules.
