### ISSUE TITLE
Perfect Paragon

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#628]
- **text:** A minion with negative intercept amount cant block an action with zero stealth
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/ze7FHSIdaA4/m/5l5rSNheHfsJ

**Comment by lionel-panhaleux** [comment]
1. This is not a proper ruling. https://groups.google.com/g/rec.games.trading-cards.jyhad/c/RY27OU0LoTU/m/g3JgxrQfQMsJ would have been (it needs to be a post from a Rules Director / Rulings Ref / Rulings Team)

2. Stealth, Intercept and Bleed and Hunt amounts can be negative, because nothing in the rulebook says otherwise. In the next rulebook iteration, hopefully, this gets included more clearly. In the meantime, I'd rather wait because adding a ruling for this would take time (there are dozen of cards providing potential negative values), only to remove them once the rulebook is updated.

**Comment by lionel-panhaleux** [comment]
Now more explicit in the v1.1 rulebook:
> Additionally, some cards and other effects can be used to increase or decrease (even below 0) a minion’s stealth or intercept, as noted on card text.
