### ISSUE TITLE
Clandestine Contract

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#671]
- **text:** Mata cannot play Provisions of the Silsila
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/vSOt2c1uRzQ/m/F4ZIvIyp7lcJ

**Comment by lionel-panhaleux** [comment]
OK, so, that's really ruling 3 here:
> When playing a card requiring a sect and/or a clan, she is treated as a such for all effects of the card, and only them, including duration effects. She is not treated as such for effects the card has from being in play.
It's not that she cannot play Provisions altogether, it's that she's not chosen for the Clandestine Contract because that's an effect of the card in play.
_Most_ contracts (except Haqim's Law: Leadership) have a different wording and, for them, she's chosen when the card is played, so she could play Provisions (see [LSJ 20071109](https://groups.google.com/g/rec.games.trading-cards.jyhad/c/mXspOwNnPDc/m/UJAVuSqFBNoJ).

So all that ruling says is she cannot play Provisions of the Silsila after a Clandestine Contract on a vampire.

I would rather _not_ list all specific card interactions in the Mata rulings. But I agree this contract choice is a specifically difficult one, so I'll add it separately.
