### ISSUE TITLE
Fear of the Void Below

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#698]
- **text:** Sets the range the moment it is played (eg. OtH damage would be long). Should apply to Neutral Guard, Sniper Rifle, etc.
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/j98aqFIFjnE/m/6yTbvCofUiIJ

**Comment by lionel-panhaleux** [comment]
Fear of the void below does *not* set the range: it makes it so that the range _defaults_ too long. So it makes sense to list it there. For cards the _do_ set the range, I cannot imagine a wording that makes it clearer than the card text (ie. when it says it "sets the range", it does set the range...) I'll add a ruling on OtH instead (probably more relevant actually).
