### ISSUE TITLE
locked T.J. and referendum - "Lock X to do Y" template

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#82]
im not sure if you need this,but i asked in forum because some reaction card say only by unlocked/but can be used with wake efect,so i ask if Tj is locked can be used,answer is-no  http://www.vekn.net/forum/rules-questions/78623-locked-t-j-and-referendum

**Comment by lionel-panhaleux** [comment]
I'm unsure about that - It's a grey line for me when to include or not "rulings" that are in fact just now in the rulebook.

**Comment by lionel-panhaleux** [comment]
For now I'd say I'm not inclined to include rulings that are answered by rulebook "templates" - but if you feel strongly otherwise (eg. if the question seems to arise often during games), we can include the rulebook precision in all concerned cards. That's a lot of "spurious" ruling in my opinion.

**Comment by warwar1980** [comment]
understand,i anyway say: im not sure if you need this,i asked because you know how rules be strange sometimes,you never can be sure if you dont ask :)

**Comment by lionel-panhaleux** [comment]
Well, I discussed it a bit with Ossian today, and I could be swayed the other way.
In this case, we should include rulings for all concerned cards for all templates:

- “Add X blood/counters”
- “Cancel a card”
- “During X, do Y”
- “Lock X to do Y”
- "Search"

I think it should be easy enough to find a ruling for each of the other 4, plus we could refer to the rulebook as [RBK 20181001](http://www.vekn.net/rulebook/11-special-terms).

The tricky part will be to put each ruling on the right card, but I can find them with text search tools easily enough I hope.

**Comment by warwar1980** [comment]
if you have link with lsj,pascal,or ankha word as rule that is best, stuf x and y can confuse people,i beleive you know that. but if you think use for future  [RBK 20181001] im ok,but pls dont remove links whu you add until now

**Comment by lionel-panhaleux** [comment]
No, of course not. I was thinking maybe adding both a rulebook and additional link if possible.

**Comment by warwar1980** [comment]
that is ok if you want,i think you go to delete links witk lsj and ankha rules

**Comment by lionel-panhaleux** [comment]
Let's do that. I'll keep this issue of the "Lock X, do Y" template and open other ones for the other templates.

I did some preliminary digging, and it seems doable for all but for the "During X, do Y" template. That one literally is on hundreds of cards...

**Comment by lionel-panhaleux** [comment]
Okay so I browsed the card a bit. Even the "lock X to do Y" template is used on hundreds of them. We could restrict it to non-master cards that do not use the "you may lock" or "you can lock" wordings (seems to be clearer somehow) but that's already stretching it.

When restricting at maximum, we come to the "not-so-obvious" cards like Babble at superior "[DEM] Lock this vampire to unlock another ready minion" or War Ghoul's "Lock and burn War Ghoul to burn any location", where I fell having indeed a specific RD link would be better (not just rulebook or T.J.'s ruling).

So all in all, for now I'll just add the ruling to T.J. with RD (Ankha) link *and* the rulebook reference. I'll encourage other contributors to add rulebook references when it makes sense, but always with an RD link upfront.

If someone feels up to it, an interesting course of action would be to list the cards where it's "not so obvious" they match the template and see if Ankha could publish a global ruling for all of those, so that we can reference the rule in bulk.

**Comment by warwar1980** [comment]
I see,you add for T.J. rule,is ok you idea x do y,but if exist link with rule special for single card,that is beter,you know,some people is stil confused about x do y,sometime maybe me too

**Comment by lionel-panhaleux** [comment]
Yeah, it would be better to have a specific ruling for each case, we'll try
that for now.

*Lionel Panhaleux*
☏ +33 6 78 98 75 13
✉︎ 134 rue Ordener, 75018 Paris
